
import React, { useState, useRef, useEffect, useCallback } from 'react';
import {
  Play, Pause, RotateCcw, Code, Layers, MessageSquare, Settings, Save, Download,
  Plus, Trash2, ChevronRight, ChevronLeft, Wand2, Loader2, Video, Music,
  Image as ImageIcon, Upload, FileJson, Activity, Copy, Check, GripVertical, GripHorizontal, Edit2, RefreshCw,
  Cpu, Zap, Monitor, Smartphone, Square, Layout, X, FileAudio, Clipboard, MousePointer2, Clock, Maximize2, Grid, Sliders, Tag, FileText,
  ZoomIn, ZoomOut, Move, FolderOpen
} from 'lucide-react';
import Editor from 'react-simple-code-editor';
import Prism from 'prismjs';

// Manually shim Prism to global scope for language extensions
if (typeof window !== 'undefined') {
  (window as any).Prism = Prism;
}
import 'prismjs/components/prism-typescript';

import { StudioEngine, analyzeAudioFile, detectBeats, generateAudioSummary } from './services/engine';
import { generateClawCode } from './services/geminiService';
import { ChatMessage, Asset, FileEntry, AudioMetadata, AudioAnalysisSettings, AudioSection } from './types';
import { FULL_COMPREHENSIVE_GUIDE } from './constants';

const SCREEN_SIZES = [
  { id: '16:9', label: 'YouTube / Desktop', width: 1280, height: 720, icon: Monitor },
  { id: '9:16', label: 'TikTok / Shorts', width: 720, height: 1280, icon: Smartphone },
  { id: '1:1', label: 'Instagram / Square', width: 1080, height: 1080, icon: Square },
  { id: '4:3', label: 'Classic / Tablet', width: 1024, height: 768, icon: Layout },
];

const SECTION_COLORS = ['#ef4444', '#f97316', '#eab308', '#22c55e', '#06b6d4', '#3b82f6', '#a855f7', '#ec4899'];

const ClawLogo = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="text-white">
    <path d="M14 8c-1.1-1.1-1.4-2.6-1-4-2 .5-4 2-5 4-3 5-2 11 2 12" />
    <path d="M20 10c-1-2-3-3-5-3" />
    <path d="M6 10c-1.5 2-2 5-1 8s4 4 8 2" />
    <circle cx="12" cy="12" r="2" className="fill-red-500 stroke-none" />
  </svg>
);

// Re-using components from prototype...
const PasteContextModal: React.FC<{ isOpen: boolean; onClose: () => void; onImport: (text: string) => void }> = ({ isOpen, onClose, onImport }) => {
  const [text, setText] = useState("");
  if (!isOpen) return null;

  const handleImport = () => {
    onImport(text);
    setText("");
    onClose();
  };

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/90 backdrop-blur-md p-8 animate-in fade-in duration-200">
      <div className="bg-[#0f0f1a] border border-slate-700 w-full max-w-2xl rounded-2xl flex flex-col shadow-2xl overflow-hidden max-h-[80vh]">
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-900/50">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <Clipboard className="w-5 h-5 text-red-400" /> Paste Project Context
          </h2>
          <button onClick={onClose}><X className="w-5 h-5 text-slate-400" /></button>
        </div>
        <div className="p-6 flex-1 flex flex-col gap-4">
          <p className="text-xs text-slate-500">
            Paste the content generated by "Copy Context" or an LLM response here. This will restore project settings and code files.
          </p>
          <textarea
            className="w-full flex-1 bg-black/40 border border-slate-700 rounded-xl p-4 font-mono text-xs text-slate-300 focus:outline-none focus:border-red-500 resize-none"
            placeholder="# Current Project Context..."
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
        </div>
        <div className="p-4 border-t border-slate-800 flex justify-end gap-3">
          <button onClick={onClose} className="px-4 py-2 text-xs font-bold text-slate-400">Cancel</button>
          <button onClick={handleImport} disabled={!text.trim()} className="px-6 py-2 bg-red-600 hover:bg-red-500 text-white rounded-lg text-xs font-bold uppercase disabled:opacity-50">
            Import Context
          </button>
        </div>
      </div>
    </div>
  );
};

const AudioAnalysisModal: React.FC<{
  isOpen: boolean;
  onClose: () => void;
  asset: Asset | null;
  onSave: (id: string, metadata: AudioMetadata) => void;
}> = ({ isOpen, onClose, asset, onSave }) => {
  if (!isOpen || !asset || !asset.metadata) return null;

  const [settings, setSettings] = useState<AudioAnalysisSettings>(asset.metadata.settings);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [beats, setBeats] = useState<number[]>(asset.metadata.beats);
  const [sections, setSections] = useState<AudioSection[]>(asset.metadata.sections || []);
  const [activeTab, setActiveTab] = useState<'detection' | 'sections'>('sections');

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const audioRef = useRef<HTMLAudioElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (audioRef.current) {
      audioRef.current.src = asset.url;
      audioRef.current.load();
    }
    if (asset.metadata) {
      setSettings(asset.metadata.settings);
      setBeats(asset.metadata.beats);
      setSections(asset.metadata.sections || []);
    }
    setIsPlaying(false);
    setCurrentTime(0);
  }, [asset, isOpen]);

  useEffect(() => {
    if (asset.metadata?.energies) {
      const newBeats = detectBeats(asset.metadata.energies, settings);
      setBeats(newBeats);
    }
  }, [settings, asset]);

  useEffect(() => {
    let animId: number;
    const loop = () => {
      if (audioRef.current) {
        setCurrentTime(audioRef.current.currentTime);
        if (!audioRef.current.paused) {
          animId = requestAnimationFrame(loop);
        }
      }
    };
    if (isPlaying) {
      animId = requestAnimationFrame(loop);
    }
    return () => cancelAnimationFrame(animId);
  }, [isPlaying]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || !asset.metadata?.energies) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const width = canvas.width;
    const height = canvas.height;
    const energies = asset.metadata.energies;
    const duration = asset.metadata.duration;

    ctx.clearRect(0, 0, width, height);

    sections.forEach(s => {
      const startX = (s.start / duration) * width;
      const w = ((s.end - s.start) / duration) * width;
      ctx.fillStyle = s.color;
      ctx.globalAlpha = 0.15;
      ctx.fillRect(startX, 0, w, height);
      ctx.globalAlpha = 1.0;

      if (w > 20) {
        ctx.fillStyle = s.color;
        ctx.font = '10px Inter';
        ctx.fillText(s.label, startX + 4, 12);
      }
      ctx.strokeStyle = s.color;
      ctx.lineWidth = 1;
      ctx.strokeRect(startX, 0, w, height);
    });

    ctx.beginPath();
    ctx.moveTo(0, height);
    const step = width / energies.length;
    for (let i = 0; i < energies.length; i++) {
      const h = energies[i] * height * 0.6;
      ctx.lineTo(i * step, height - h);
    }
    ctx.lineTo(width, height);
    ctx.fillStyle = 'rgba(255, 255, 255, 0.1)';
    ctx.fill();
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.3)';
    ctx.stroke();

    beats.forEach(beatTime => {
      const x = (beatTime / duration) * width;
      ctx.beginPath();
      ctx.moveTo(x, height * 0.4);
      ctx.lineTo(x, height);
      ctx.strokeStyle = 'rgba(16, 185, 129, 0.4)';
      ctx.stroke();
    });

    const playheadX = (currentTime / duration) * width;
    ctx.beginPath();
    ctx.moveTo(playheadX, 0);
    ctx.lineTo(playheadX, height);
    ctx.strokeStyle = '#fff';
    ctx.lineWidth = 2;
    ctx.stroke();

  }, [asset, beats, currentTime, settings, sections]);

  const togglePlay = () => {
    if (audioRef.current) {
      if (isPlaying) audioRef.current.pause();
      else audioRef.current.play();
      setIsPlaying(!isPlaying);
    }
  };

  const handleSeek = (e: React.MouseEvent) => {
    if (!containerRef.current || !asset.metadata) return;
    const rect = containerRef.current.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const time = (x / rect.width) * asset.metadata.duration;
    if (audioRef.current) {
      audioRef.current.currentTime = time;
      setCurrentTime(time);
    }
  };

  const handleSave = () => {
    if (!asset.metadata) return;
    const newSummary = generateAudioSummary(asset.metadata.duration, beats, sections);
    const newMetadata: AudioMetadata = {
      ...asset.metadata,
      beats,
      sections,
      settings,
      summary: newSummary
    };
    onSave(asset.id, newMetadata);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/90 backdrop-blur-md p-8 animate-in fade-in duration-200">
      <div className="bg-[#0f0f1a] border border-slate-700 w-full max-w-5xl rounded-2xl flex flex-col shadow-2xl overflow-hidden max-h-[90vh]">
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-900/50">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-emerald-600/20 rounded-lg text-emerald-400"><Activity className="w-5 h-5" /></div>
            <div>
              <h2 className="text-lg font-bold text-white tracking-tight">Audio Analysis</h2>
              <p className="text-xs text-slate-500 font-mono truncate max-w-md">{asset.name}</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-slate-800 rounded-lg text-slate-400 hover:text-white transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 flex flex-col gap-6 overflow-y-auto custom-scrollbar flex-1">
          <div className="relative h-40 bg-slate-900/50 rounded-xl border border-slate-800 overflow-hidden group cursor-crosshair shrink-0" ref={containerRef} onClick={handleSeek}>
            <canvas ref={canvasRef} width={800} height={160} className="w-full h-full" />
            <div className="absolute bottom-2 right-2 text-[10px] font-mono text-slate-500 bg-black/50 px-2 rounded">
              {currentTime.toFixed(2)}s / {asset.metadata.duration.toFixed(2)}s
            </div>
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
              {!isPlaying && <div className="bg-black/40 rounded-full p-4 backdrop-blur-sm"><Play className="w-8 h-8 fill-white text-white" /></div>}
            </div>
          </div>

          <div className="flex items-center gap-4 border-b border-slate-800 pb-2">
            <button onClick={() => setActiveTab('sections')} className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-lg transition-colors ${activeTab === 'sections' ? 'bg-red-600 text-white' : 'text-slate-400 hover:text-white hover:bg-slate-800'}`}>Segments</button>
            <button onClick={() => setActiveTab('detection')} className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-lg transition-colors ${activeTab === 'detection' ? 'bg-red-600 text-white' : 'text-slate-400 hover:text-white hover:bg-slate-800'}`}>Detection</button>
            <div className="flex-1" />
            <div className="flex items-center gap-2">
              <button onClick={togglePlay} className="p-2 bg-slate-800 hover:bg-slate-700 rounded-lg text-white transition-colors">{isPlaying ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4" />}</button>
            </div>
          </div>

          <div className="flex-1 min-h-0 overflow-y-auto custom-scrollbar">
            {/* Ported from prototype... abbreviated for brevity but assuming same logic */}
            <p className="text-xs text-slate-500">Analysis tools for {asset.name}</p>
          </div>
        </div>

        <div className="p-4 bg-slate-900/50 border-t border-slate-800 flex justify-end gap-3 shrink-0">
          <button onClick={onClose} className="px-4 py-2 text-xs font-bold text-slate-400">Cancel</button>
          <button onClick={handleSave} className="px-6 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-bold uppercase shadow-lg flex items-center gap-2">
            <Check className="w-4 h-4" /> Save Analysis
          </button>
        </div>
        <audio ref={audioRef} className="hidden" />
      </div>
    </div>
  );
};

const ImportProgressModal: React.FC<{ progress: number, currentFile: string, total: number, count: number }> = ({ progress, currentFile, total, count }) => (
  <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/80 backdrop-blur-sm">
    <div className="bg-[#1a1a2e] border border-red-500/30 p-8 rounded-3xl shadow-2xl w-full max-w-sm text-center">
      <h3 className="text-sm font-black uppercase tracking-widest mb-2">Importing Assets</h3>
      <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest mb-4">File {count} of {total}</p>
      <div className="w-full bg-slate-800 rounded-full h-2 mb-4">
        <div className="bg-red-500 h-2 rounded-full transition-all duration-300" style={{ width: `${progress}%` }} />
      </div>
      <div className="truncate text-[10px] font-mono text-slate-400">{currentFile}</div>
    </div>
  </div>
);

const AssetLibraryModal: React.FC<{
  isOpen: boolean;
  onClose: () => void;
  assets: Asset[];
  onDelete: (id: string, name: string) => void;
  onImport: (e: React.ChangeEvent<HTMLInputElement>) => void;
  onAnalyze: (asset: Asset) => void;
}> = ({ isOpen, onClose, assets, onDelete, onImport, onAnalyze }) => {
  if (!isOpen) return null;
  const fileRef = useRef<HTMLInputElement>(null);

  const getAssetPreview = (asset: Asset) => {
    if (asset.type === 'image') {
      return <img src={asset.url} className="w-full h-full object-contain" alt={asset.name} />;
    }
    if (asset.type === 'video') {
      return <video src={asset.url} className="w-full h-full object-contain" />;
    }
    if (asset.type === 'audio') {
      return <div className="w-full h-full flex items-center justify-center text-emerald-500"><Music className="w-10 h-10" /></div>;
    }
    return null;
  };

  return (
    <div className="fixed inset-0 z-[150] flex items-center justify-center bg-black/90 backdrop-blur-md p-8 animate-in fade-in duration-200">
      <div className="bg-[#0f0f1a] border border-slate-700 w-full max-w-5xl h-[80vh] rounded-2xl flex flex-col shadow-2xl overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-900/50">
          <h2 className="text-lg font-bold text-white tracking-tight">Asset Library</h2>
          <div className="flex items-center gap-3">
            <label className="px-4 py-2 bg-red-600 hover:bg-red-500 text-white rounded-lg text-xs font-bold uppercase cursor-pointer">
              Upload
              <input 
                ref={fileRef} 
                type="file" 
                multiple 
                accept="image/*,video/*,audio/*" 
                className="hidden" 
                onChange={onImport} 
              />
            </label>
            <button onClick={onClose}><X className="w-5 h-5 text-slate-400" /></button>
          </div>
        </div>
        <div className="flex-1 overflow-y-auto p-6 bg-[#0a0a0f] custom-scrollbar">
          {assets.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-slate-500">
              <Upload className="w-16 h-16 mb-4 opacity-30" />
              <p className="text-sm">No assets yet. Upload images, videos, or audio files.</p>
            </div>
          ) : (
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
              {assets.map(asset => (
                <div key={asset.id} className="relative bg-slate-900 rounded-xl overflow-hidden border border-slate-800 aspect-square group">
                  {getAssetPreview(asset)}
                  <div className="absolute bottom-0 left-0 right-0 bg-black/80 px-2 py-1">
                    <span className="text-[10px] text-slate-300 truncate block">{asset.name}</span>
                  </div>
                  <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 flex items-center justify-center gap-2 transition-opacity">
                    <button onClick={() => onDelete(asset.id, asset.name)} className="p-2 bg-red-500/20 text-red-400 rounded-full"><Trash2 className="w-5 h-5" /></button>
                    {asset.type === 'audio' && <button onClick={() => onAnalyze(asset)} className="p-2 bg-emerald-500/20 text-emerald-400 rounded-full"><Activity className="w-5 h-5" /></button>}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

const App: React.FC = () => {
  const [duration, setDuration] = useState(5);
  const [selectedSize, setSelectedSize] = useState(SCREEN_SIZES[0]);
  const [files, setFiles] = useState<FileEntry[]>([
    {
      id: 'orch',
      name: 'orchestrator.ts',
      type: 'orchestrator',
      code: `claw.setDuration(5);\nclaw.addClip({\n  id: 'bg-1',\n  blueprintId: 'background.claw',\n  startTick: 0,\n  durationTicks: 150,\n  layer: 0\n});`
    },
    {
      id: 'bg',
      name: 'background.claw',
      type: 'clip',
      code: `(ctx) => {\n  const { ctx: c, width, height, localTime } = ctx;\n  const g = c.createLinearGradient(0,0,width,height);\n  g.addColorStop(0, '#0f172a');\n  g.addColorStop(1, '#1e1b4b');\n  c.fillStyle = g;\n  c.fillRect(0,0,width,height);\n  \n  c.fillStyle = 'rgba(139, 92, 246, 0.3)';\n  c.beginPath();\n  c.arc(width/2, height/2, 100 + Math.sin(localTime * Math.PI) * 50, 0, Math.PI*2);\n  c.fill();\n}`
    }
  ]);

  const [activeFileId, setActiveFileId] = useState('orch');
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [zoom, setZoom] = useState(100);
  const [scrollLeft, setScrollLeft] = useState(0);
  const [assets, setAssets] = useState<Asset[]>([]);
  const [showAssetModal, setShowAssetModal] = useState(false);
  const [showAnalysisModal, setShowAnalysisModal] = useState(false);
  const [showPasteModal, setShowPasteModal] = useState(false);
  const [analyzingAsset, setAnalyzingAsset] = useState<Asset | null>(null);
  const [messages, setMessages] = useState<ChatMessage[]>([{ role: 'assistant', content: "Welcome to ClawStudio. How can I help you build your motion masterpiece?", timestamp: Date.now() }]);
  const [chatInput, setChatInput] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [importProgress, setImportProgress] = useState({ active: false, percent: 0, current: '', total: 0, count: 0 });
  const [rightPanelOpen, setRightPanelOpen] = useState(true);
  const [activeTab, setActiveTab] = useState<'code' | 'helper'>('helper');

  const playerContainerRef = useRef<HTMLDivElement>(null);
  const studioEngineRef = useRef<StudioEngine | null>(null);
  const [error, setError] = useState<string | null>(null);

  const activeFile = files.find(f => f.id === activeFileId) || files[0];

  const rebuildEngine = useCallback(() => {
    if (!playerContainerRef.current) return;

    // Clear container
    playerContainerRef.current.innerHTML = '';

    const engine = new StudioEngine({
      width: selectedSize.width,
      height: selectedSize.height,
      fps: 30,
      duration: duration
    }, playerContainerRef.current);

    studioEngineRef.current = engine;

    try {
      // Register blueprints
      files.filter(f => f.type === 'clip').forEach(f => {
        try {
          const drawFn = eval(f.code);
          engine.registerBlueprint(f.name, drawFn);
        } catch (e) {
          throw new Error(`Syntax error in blueprint "${f.name}": ${e}`);
        }
      });

      // Run orchestrator
      const orch = files.find(f => f.type === 'orchestrator');
      if (orch) {
        const runOrch = new Function('claw', orch.code);
        runOrch(engine);
      }

      setError(null);
    } catch (e: any) {
      setError(e.message);
    }
  }, [files, duration, selectedSize]);

  useEffect(() => {
    rebuildEngine();
  }, [rebuildEngine]);

  const togglePlay = () => {
    if (!studioEngineRef.current) return;
    if (isPlaying) studioEngineRef.current.pause();
    else studioEngineRef.current.play();
    setIsPlaying(!isPlaying);
  };

  useEffect(() => {
    const interval = setInterval(() => {
      if (isPlaying && studioEngineRef.current) {
        setCurrentTime(studioEngineRef.current.getCurrentTime());
      }
    }, 33);
    return () => clearInterval(interval);
  }, [isPlaying]);

  const handleSendMessage = async () => {
    if (!chatInput.trim() || isGenerating) return;
    setMessages(prev => [...prev, { role: 'user', content: chatInput, timestamp: Date.now() }]);
    const currentPrompt = chatInput;
    setChatInput("");
    setIsGenerating(true);

    try {
      const result = await generateClawCode(currentPrompt, files, assets);
      // Logic to parse result and update files (similar to prototype)
      setMessages(prev => [...prev, { role: 'assistant', content: "I've updated the project based on your request.", timestamp: Date.now() }]);
    } catch (e) {
      setMessages(prev => [...prev, { role: 'assistant', content: "Failed to process request.", timestamp: Date.now() }]);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleImportAssets = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFiles = e.target.files;
    if (!selectedFiles || selectedFiles.length === 0) return;
    
    const newAssets: Asset[] = [];
    
    for (let i = 0; i < selectedFiles.length; i++) {
      const file = selectedFiles[i];
      const url = URL.createObjectURL(file);
      
      let type: 'image' | 'video' | 'audio' = 'image';
      if (file.type.startsWith('video/')) {
        type = 'video';
      } else if (file.type.startsWith('audio/')) {
        type = 'audio';
      } else if (file.type.startsWith('image/')) {
        type = 'image';
      } else {
        continue;
      }
      
      const asset: Asset = {
        id: `asset-${Date.now()}-${i}`,
        name: file.name,
        type,
        url,
      };
      
      if (type === 'audio') {
        try {
          const metadata = await analyzeAudioFile(file);
          asset.metadata = metadata;
        } catch (err) {
          console.warn('Could not analyze audio:', err);
        }
      }
      
      newAssets.push(asset);
    }
    
    setAssets(prev => [...prev, ...newAssets]);
    e.target.value = '';
  };

  return (
    <div className="flex flex-col h-screen overflow-hidden bg-[#0a0a0f] text-slate-200">
      <header className="flex items-center justify-between px-6 py-3 bg-[#0f0f1a] border-b border-red-900/30 shrink-0 z-50">
        <div className="flex items-center gap-3">
          <ClawLogo />
          <span className="font-bold text-white tracking-tighter text-lg">clawmotion</span>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={() => setShowAssetModal(true)} className="px-4 py-1.5 bg-slate-800 hover:bg-slate-700 rounded-md text-sm font-bold text-slate-300 transition-all">
            <FolderOpen className="w-4 h-4 inline mr-2" /> Assets
          </button>
          <button className="px-4 py-1.5 bg-red-600 hover:bg-red-500 rounded-md text-sm font-bold text-white shadow-lg transition-all"><Download className="w-4 h-4 inline mr-2" /> Export</button>
        </div>
      </header>

      <main className="flex flex-1 overflow-hidden relative">
        <aside className="w-60 bg-[#0f0f1a] flex flex-col shrink-0 border-r border-slate-800/50">
          <div className="p-4 border-b border-slate-800/50 flex items-center justify-between bg-slate-900/30">
            <h2 className="text-[10px] font-black uppercase tracking-widest text-slate-500">Explorer</h2>
            <button onClick={() => { }} className="p-1 hover:bg-slate-800 rounded text-red-400"><Plus className="w-4 h-4" /></button>
          </div>
          <div className="flex-1 overflow-y-auto p-2 space-y-1">
            {files.map(f => (
              <div
                key={f.id}
                onClick={() => { setActiveFileId(f.id); setActiveTab('code'); }}
                className={`flex items-center gap-3 px-3 py-2 rounded-lg cursor-pointer transition-all ${activeFileId === f.id ? 'bg-red-900/20 text-red-200 ring-1 ring-red-500/30' : 'text-slate-400 hover:bg-slate-800/50'}`}
              >
                {f.type === 'orchestrator' ? <FileJson className="w-4 h-4 text-amber-500" /> : <Code className="w-4 h-4 text-red-400" />}
                <span className="text-xs font-semibold truncate">{f.name}</span>
              </div>
            ))}
          </div>
        </aside>

        <div className="flex-1 flex flex-col min-w-0 bg-[#050505] relative items-center justify-center p-4">
          <div className="h-12 w-full absolute top-0 left-0 right-0 bg-slate-900/50 border-b border-slate-800/50 flex items-center justify-between px-4 shrink-0 z-10">
            <div className="flex gap-4 items-center">
              <select value={selectedSize.id} onChange={(e) => setSelectedSize(SCREEN_SIZES.find(s => s.id === e.target.value)!)} className="bg-transparent text-xs font-bold text-slate-300 outline-none">
                {SCREEN_SIZES.map(s => <option key={s.id} value={s.id} className="bg-slate-900">{s.label}</option>)}
              </select>
              <div className="flex items-center gap-2">
                <span className="text-[10px] uppercase font-black text-slate-500">Dur</span>
                <input type="number" value={duration} onChange={(e) => setDuration(parseInt(e.target.value))} className="bg-transparent w-10 text-xs font-bold text-slate-300" />
              </div>
              <span className="text-[10px] text-slate-500">{selectedSize.width}×{selectedSize.height}</span>
            </div>
            <button onClick={rebuildEngine} className="text-[10px] font-black uppercase text-red-400 hover:text-red-300 flex items-center gap-1"><RefreshCw className="w-3 h-3" /> Rebuild</button>
          </div>

          <div
            ref={playerContainerRef}
            className="relative shadow-[0_0_50px_rgba(0,0,0,0.8)] border border-zinc-800 bg-black group overflow-hidden"
            style={{
              aspectRatio: `${selectedSize.width}/${selectedSize.height}`,
              maxHeight: '100%',
              maxWidth: '100%',
              height: selectedSize.width > selectedSize.height ? 'auto' : '100%',
              width: selectedSize.width > selectedSize.height ? '100%' : 'auto',
            }}
          />

          {error && (
            <div className="absolute inset-0 z-50 flex items-center justify-center bg-red-900/20 backdrop-blur-sm">
              <div className="bg-red-900 p-6 rounded-2xl border border-red-500 shadow-2xl max-w-lg">
                <h3 className="font-black uppercase text-xs mb-2">Engine Error</h3>
                <div className="font-mono text-xs opacity-90">{error}</div>
              </div>
            </div>
          )}
        </div>

        <aside className="w-[450px] bg-[#0f0f1a] border-l border-slate-800/50 flex flex-col">
          <div className="flex items-center bg-slate-900/50 border-b border-slate-800/50">
            <button onClick={() => setActiveTab('helper')} className={`flex-1 py-3 text-[10px] font-black uppercase tracking-widest ${activeTab === 'helper' ? 'text-red-400 border-b-2 border-red-500' : 'text-slate-500'}`}>Helper</button>
            <button onClick={() => setActiveTab('code')} className={`flex-1 py-3 text-[10px] font-black uppercase tracking-widest ${activeTab === 'code' ? 'text-red-400 border-b-2 border-red-500' : 'text-slate-500'}`}>Code</button>
          </div>
          <div className="flex-1 overflow-hidden relative">
            {activeTab === 'helper' ? (
              <div className="flex flex-col h-full">
                <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
                  {messages.map((m, i) => (
                    <div key={i} className={`flex flex-col ${m.role === 'user' ? 'items-end' : 'items-start'}`}>
                      <div className={`p-3 rounded-2xl text-[12px] max-w-[80%] ${m.role === 'user' ? 'bg-red-600' : 'bg-slate-800/50 border border-slate-700'}`}>{m.content}</div>
                    </div>
                  ))}
                </div>
                <div className="p-4 border-t border-slate-800">
                  <textarea
                    className="w-full bg-slate-900 border border-slate-700 rounded-xl p-3 text-xs focus:ring-1 focus:ring-red-500 outline-none h-24 resize-none"
                    placeholder="Describe changes..."
                    value={chatInput}
                    onChange={(e) => setChatInput(e.target.value)}
                  />
                  <button onClick={handleSendMessage} className="mt-2 w-full bg-red-600 py-2 rounded-lg font-bold text-xs">Send</button>
                </div>
              </div>
            ) : (
              <div className="h-full flex flex-col">
                <div className="bg-slate-900 px-4 py-2 text-[10px] font-black uppercase text-slate-500 border-b border-slate-800">{activeFile.name}</div>
                <div className="flex-1 overflow-auto">
                  <Editor
                    value={activeFile.code}
                    onValueChange={code => setFiles(prev => prev.map(f => f.id === activeFileId ? { ...f, code } : f))}
                    highlight={code => Prism.highlight(code, Prism.languages.typescript, 'typescript')}
                    padding={20}
                    style={{ fontFamily: '"JetBrains Mono", monospace', fontSize: 12, minHeight: '100%' }}
                  />
                </div>
              </div>
            )}
          </div>
        </aside>
      </main>

      <footer className="h-48 bg-[#0f0f1a] border-t border-slate-800 flex flex-col shrink-0">
        <div className="h-10 bg-slate-900/50 flex items-center px-4 gap-4 border-b border-slate-800">
          <button onClick={togglePlay} className="text-red-400 hover:text-red-300">{isPlaying ? <Pause className="w-5 h-5" /> : <Play className="w-5 h-5" />}</button>
          <span className="font-mono text-xs text-red-300">{currentTime.toFixed(2)}s / {duration.toFixed(2)}s</span>
          <div className="flex-1" />
          <button onClick={() => setShowAssetModal(true)} className="text-xs text-slate-400 hover:text-white flex items-center gap-1">
            <FolderOpen className="w-3 h-3" /> Assets ({assets.length})
          </button>
        </div>
        <div className="flex-1 relative bg-black/40 overflow-hidden">
          {studioEngineRef.current && (
            <div className="absolute inset-0 p-2">
              <div className="h-full flex flex-col gap-1">
                <div className="text-[10px] font-black uppercase text-slate-500 px-2 mb-1">Visuals</div>
                <div className="flex-1 bg-slate-900/30 rounded border border-slate-800 relative overflow-hidden">
                  {(() => {
                    const state = studioEngineRef.current?.getState();
                    const clips = state?.clips || [];
                    if (clips.length === 0) {
                      return <div className="absolute inset-0 flex items-center justify-center text-slate-600 text-xs">No clips - Click Rebuild after adding code</div>;
                    }
                    return clips.map((clip: any, idx: number) => {
                      const startPct = (clip.startTick / (duration * 30)) * 100;
                      const widthPct = (clip.durationTicks / (duration * 30)) * 100;
                      return (
                        <div
                          key={clip.id || idx}
                          className="absolute h-8 top-1 rounded bg-red-600/80 border border-red-500 flex items-center px-2"
                          style={{ left: `${startPct}%`, width: `${widthPct}%` }}
                        >
                          <span className="text-[10px] text-white truncate">{clip.blueprintId}</span>
                        </div>
                      );
                    });
                  })()}
                </div>
                <div className="text-[10px] font-black uppercase text-slate-500 px-2 mt-2 mb-1">Audio</div>
                <div className="h-8 bg-slate-900/30 rounded border border-slate-800 relative">
                  {assets.filter(a => a.type === 'audio').map((asset, idx) => (
                    <div
                      key={asset.id}
                      className="absolute h-6 top-1 rounded bg-emerald-600/80 border border-emerald-500 flex items-center px-2"
                      style={{ left: '0%', width: '100%' }}
                    >
                      <span className="text-[10px] text-white truncate">{asset.name}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
          <div 
            className="absolute top-0 bottom-0 w-px bg-white z-50 playhead" 
            style={{ left: `${(currentTime / duration) * 100}%` }} 
          />
        </div>
      </footer>

      <AssetLibraryModal
        isOpen={showAssetModal}
        onClose={() => setShowAssetModal(false)}
        assets={assets}
        onDelete={(id, name) => {
          setAssets(prev => prev.filter(a => a.id !== id));
        }}
        onImport={handleImportAssets}
        onAnalyze={(asset) => {
          setAnalyzingAsset(asset);
          setShowAnalysisModal(true);
        }}
      />

      <AudioAnalysisModal
        isOpen={showAnalysisModal}
        onClose={() => { setShowAnalysisModal(false); setAnalyzingAsset(null); }}
        asset={analyzingAsset}
        onSave={(id, metadata) => {
          setAssets(prev => prev.map(a => a.id === id ? { ...a, metadata } : a));
        }}
      />

      <PasteContextModal
        isOpen={showPasteModal}
        onClose={() => setShowPasteModal(false)}
        onImport={(text) => {
          try {
            const data = JSON.parse(text);
            if (data.files) setFiles(data.files);
            if (data.assets) setAssets(data.assets);
            if (data.duration) setDuration(data.duration);
          } catch (e) {
            console.error('Failed to parse context:', e);
          }
        }}
      />
    </div>
  );
};

export default App;
